#!/usr/bin/env bash

GIF=$1
NAME=$(echo "${1##*/}" | cut -d. -f1)
DIR=$HOME/Pictures/live/hm-theme/"$NAME"
GO_DIR=$HOME/.cache/tmp-go
FF_DIR=$HOME/.cache/tmp-png

rm -rf $FF_DIR && rm -rf $GO_DIR &&
mkdir -p $FF_DIR
mkdir -p $GO_DIR
mkdir -p $DIR

ffmpeg -i $GIF $FF_DIR/frame_%04d.png &&
gowall convert --dir "$FF_DIR" --output "$GO_DIR" -f "png" -t "hm-theme" &&
ffmpeg -pattern_type glob -i "$GO_DIR/*.png" -c:v bmp $DIR/%d.bmp &&

rm -rf $FF_DIR && rm -rf $GO_DIR
