#!/bin/bash

LOCKFILE="$HOME/.cache/bspwm-cmaster-oneshot-$DESKTOP.lock"

# Prevent multiple instances
if [[ -f "$LOCKFILE" ]] && kill -0 "$(cat "$LOCKFILE")" 2>/dev/null; then
    exit 0
fi

# Record current PID in lock file
echo $$ > "$LOCKFILE"

# Ensure lock file is removed when script exits
trap 'rm -f "$LOCKFILE"' EXIT





windowcount=$(bspc query -N -n .window.!floating.!hidden -d focused | wc -l)

#case "$windowcount" in
#    0) exit 0 ;;
#esac

# 1 2 3 10+ windows, exit
#case "$windowcount" in
#    1|2|[1-9][0-9]*) exit 0 ;;  # 1,2,3, or 10+
#esac


# 0 window
if [ "$windowcount" -eq 0 ]; then
  echo "no windows detected on workspace"
  exit
fi

# 1 window
if [ "$windowcount" -eq 1 ]; then
  echo "only one window detected"
  exit
fi

# 2 window
if [ "$windowcount" -eq 2 ]; then

DESKTOP=$(bspc query -D -d focused)
FOCUSED_WIN=$(bspc query -N -n focused)
LAST_WIN=$(bspc query -N -n last)
TERM_TRACK_FILE="/tmp/bsp-center_master_spawned_terminal_$DESKTOP"
PID_FILE="$HOME/.cache/bsp-center_master_terminal_pid_$DESKTOP"

  if bspc query -N -n ".local.!hidden" -d focused | grep -qx "$LAST_WIN"; then
      bspc node "$LAST_WIN" -f
  fi
  [ -n "$FOCUSED_WIN" ] && bspc node "$FOCUSED_WIN" -f
  bspc node -s east
  bspc node -s east
  bspc query -N -d | xargs -I % bspc node % -B
  bspc node -z left -240 0
  exit
fi



# 3 windows
if [ "$windowcount" -eq 3 ]; then

DESKTOP=$(bspc query -D -d focused)
FOCUSED_WIN=$(bspc query -N -n focused)
LAST_WIN=$(bspc query -N -n last)
TERM_TRACK_FILE="/tmp/bsp-center_master_spawned_terminal_$DESKTOP"
PID_FILE="$HOME/.cache/bsp-center_master_terminal_pid_$DESKTOP"

windows=($(bspc query -N -n .window.!floating.!hidden -d focused))
master=${windows[0]}
stack=("${windows[@]:1}")
cols=($(bspc query -N -n .leaf -d focused))
left=${cols[0]}
center=${cols[1]}
right=${cols[2]}


bsp-vertical-layout-oneshot
bspc node -s east
bspc node -s east
bspc node -s west

    bspc node -z left -150 0
    bspc node -z right 150 0
    #bsp-zoom

    if bspc query -N -n ".local.!hidden" -d focused | grep -qx "$LAST_WIN"; then
        bspc node "$LAST_WIN" -f
    fi
    [ -n "$FOCUSED_WIN" ] && bspc node "$FOCUSED_WIN" -f
    bspc node "$(bspc query -N -n focused)" -s "$(bspc query -N -n biggest.local)"

    exit
fi


# 5 windows
if [ "$windowcount" -eq 5 ]; then

DESKTOP=$(bspc query -D -d focused)
FOCUSED_WIN=$(bspc query -N -n focused)
LAST_WIN=$(bspc query -N -n last)
TERM_TRACK_FILE="/tmp/bsp-center_master_spawned_terminal_$DESKTOP"
PID_FILE="$HOME/.cache/bsp-center_master_terminal_pid_$DESKTOP"

windows=($(bspc query -N -n .window.!floating.!hidden -d focused))
master=${windows[0]}
stack=("${windows[@]:1}")
cols=($(bspc query -N -n .leaf -d focused))
left=${cols[0]}
center=${cols[1]}
right=${cols[2]}
# 0 window , exit
[ ${#windows[@]} -eq 0 ] && exit

    bsp-layout once even

    for w in "${windows[@]}"; do
        bspc node "$w" -t tiled
    done
    bspc node "$master" -p west
    bspc node "$master" -p east
    bspc node "$master" -n "$center"
    i=0
    for w in "${stack[@]}"; do
        if (( i % 2 == 0 )); then
            bspc node "$w" -n "$left"
        else
            bspc node "$w" -n "$right"
        fi
        ((i++))
    done
    bspc node "$left" -s south
    bspc node "$right" -s south
    bspc node "$center" -f

    bsp-layout once even
    bspc node -z left -240 0
    bspc node -z right 240 0
    #bsp-zoom

    if bspc query -N -n ".local.!hidden" -d focused | grep -qx "$LAST_WIN"; then
        bspc node "$LAST_WIN" -f
    fi
    [ -n "$FOCUSED_WIN" ] && bspc node "$FOCUSED_WIN" -f
    bspc node "$(bspc query -N -n focused)" -s "$(bspc query -N -n biggest.local)"
    exit

fi


# 4 windows
if [ "$windowcount" -eq 4 ]; then

DESKTOP=$(bspc query -D -d focused)
FOCUSED_WIN=$(bspc query -N -n focused)
LAST_WIN=$(bspc query -N -n last)
TERM_TRACK_FILE="/tmp/bsp-center_master_spawned_terminal_$DESKTOP"
PID_FILE="$HOME/.cache/bsp-center_master_terminal_pid_$DESKTOP"

windows=($(bspc query -N -n .window.!floating.!hidden -d focused))
master=${windows[0]}
stack=("${windows[@]:1}")
cols=($(bspc query -N -n .leaf -d focused))
left=${cols[0]}
center=${cols[1]}
right=${cols[2]}
# 0 window , exit
[ ${#windows[@]} -eq 0 ] && exit

    bspc query -N -d | xargs -I % bspc node % -B

    for w in "${windows[@]}"; do
        bspc node "$w" -t tiled
    done
    bspc node "$master" -p west
    bspc node "$master" -p east
    bspc node "$master" -n "$center"
    i=0
    for w in "${stack[@]}"; do
        if (( i % 2 == 0 )); then
            bspc node "$w" -n "$left"
        else
            bspc node "$w" -n "$right"
        fi
        ((i++))
    done
    bspc node "$left" -s south
    bspc node "$right" -s south
    bspc node "$center" -f

TERM_TRACK_FILE="/tmp/bsp-center_master_spawned_terminal_$DESKTOP"
PID_FILE="$HOME/.cache/bsp-center_master_terminal_pid_$DESKTOP"

"$TERMINAL" >/dev/null 2>&1 &
PID=$!
printf '%s\n' "$PID" > "$HOME/.cache/bsp-center_master_terminal_pid_$DESKTOP"


windows=($(bspc query -N -n .window.!floating.!hidden -d focused))
master=${windows[0]}
stack=("${windows[@]:1}")
cols=($(bspc query -N -n .leaf -d focused))
left=${cols[0]}
center=${cols[1]}
right=${cols[2]}
# 0 window , exit
[ ${#windows[@]} -eq 0 ] && exit

    bspc query -N -d | xargs -I % bspc node % -B

    for w in "${windows[@]}"; do
        bspc node "$w" -t tiled
    done
    bspc node "$master" -p west
    bspc node "$master" -p east
    bspc node "$master" -n "$center"
    i=0
    for w in "${stack[@]}"; do
        if (( i % 2 == 0 )); then
            bspc node "$w" -n "$left"
        else
            bspc node "$w" -n "$right"
        fi
        ((i++))
    done
    bspc node "$left" -s south
    bspc node "$right" -s south
    bspc node "$center" -f


    kill -KILL "$PID"
    rm -f "$PID_FILE"


    if bspc query -N -n ".local.!hidden" -d focused | grep -qx "$LAST_WIN"; then
        bspc node "$LAST_WIN" -f
    fi
    [ -n "$FOCUSED_WIN" ] && bspc node "$FOCUSED_WIN" -f
    bspc node "$(bspc query -N -n focused)" -s "$(bspc query -N -n biggest.local)"

    bspc node -z left -150 0
    bspc node -z right 150 0

    exit

fi



# 6 windows
if [ "$windowcount" -eq 6 ]; then

DESKTOP=$(bspc query -D -d focused)
FOCUSED_WIN=$(bspc query -N -n focused)
LAST_WIN=$(bspc query -N -n last)
TERM_TRACK_FILE="/tmp/bsp-center_master_spawned_terminal_$DESKTOP"
PID_FILE="$HOME/.cache/bsp-center_master_terminal_pid_$DESKTOP"

"$TERMINAL" >/dev/null 2>&1 &
PID=$!
printf '%s\n' "$PID" > "$HOME/.cache/bsp-center_master_terminal_pid_$DESKTOP"


windows=($(bspc query -N -n .window.!floating.!hidden -d focused))
master=${windows[0]}
stack=("${windows[@]:1}")
cols=($(bspc query -N -n .leaf -d focused))
left=${cols[0]}
center=${cols[1]}
right=${cols[2]}
# 0 window , exit
[ ${#windows[@]} -eq 0 ] && exit

    for w in "${windows[@]}"; do
        bspc node "$w" -t tiled
    done
    bspc node "$master" -p west
    bspc node "$master" -p east
    bspc node "$master" -n "$center"
    i=0
    for w in "${stack[@]}"; do
        if (( i % 2 == 0 )); then
            bspc node "$w" -n "$left"
        else
            bspc node "$w" -n "$right"
        fi
        ((i++))
    done
    bspc node "$left" -s south
    bspc node "$right" -s south
    bspc node "$center" -f

windows2=($(bspc query -N -n .window.!floating.!hidden -d focused))
master2=${windows2[0]}
stack2=("${windows2[@]:1}")
cols2=($(bspc query -N -n .leaf -d focused))
left2=${cols2[0]}
center2=${cols2[1]}
right2=${cols2[2]}
# 0 window , exit
[ ${#windows2[@]} -eq 0 ] && exit

    bsp-layout once even

    for w in "${windows2[@]}"; do
        bspc node "$w" -t tiled
    done
    bspc node "$master2" -p west
    bspc node "$master2" -p east
    bspc node "$master2" -n "$center2"
    i=0
    for w2 in "${stack2[@]}"; do
        if (( i % 2 == 0 )); then
            bspc node "$w2" -n "$left2"
        else
            bspc node "$w2" -n "$right2"
        fi
        ((i++))
    done
    bspc node "$left2" -s south
    bspc node "$right2" -s south
    bspc node "$center2" -f

    kill -KILL "$PID"
    rm -f "$PID_FILE"


    if bspc query -N -n ".local.!hidden" -d focused | grep -qx "$LAST_WIN"; then
        bspc node "$LAST_WIN" -f
    fi
    [ -n "$FOCUSED_WIN" ] && bspc node "$FOCUSED_WIN" -f
    bspc node "$(bspc query -N -n focused)" -s "$(bspc query -N -n biggest.local)"

    bsp-layout once even
    bspc node -z left -375 0
    bspc node -z right 150 0

    exit
fi



# 7 windows
if [ "$windowcount" -eq 7 ]; then

DESKTOP=$(bspc query -D -d focused)
FOCUSED_WIN=$(bspc query -N -n focused)
LAST_WIN=$(bspc query -N -n last)
TERM_TRACK_FILE="/tmp/bsp-center_master_spawned_terminal_$DESKTOP"
PID_FILE="$HOME/.cache/bsp-center_master_terminal_pid_$DESKTOP"

windows=($(bspc query -N -n .window.!floating.!hidden -d focused))
master=${windows[0]}
stack=("${windows[@]:1}")
cols=($(bspc query -N -n .leaf -d focused))
left=${cols[0]}
center=${cols[1]}
right=${cols[2]}
# 0 window , exit
[ ${#windows[@]} -eq 0 ] && exit

    for w in "${windows[@]}"; do
        bspc node "$w" -t tiled
    done
    bspc node "$master" -p west
    bspc node "$master" -p east
    bspc node "$master" -n "$center"
    i=0
    for w in "${stack[@]}"; do
        if (( i % 2 == 0 )); then
            bspc node "$w" -n "$left"
        else
            bspc node "$w" -n "$right"
        fi
        ((i++))
    done
    bspc node "$left" -s south
    bspc node "$right" -s south
    bspc node "$center" -f

windows2=($(bspc query -N -n .window.!floating.!hidden -d focused))
master2=${windows2[0]}
stack2=("${windows2[@]:1}")
cols2=($(bspc query -N -n .leaf -d focused))
left2=${cols2[0]}
center2=${cols2[1]}
right2=${cols2[2]}
# 0 window , exit
[ ${#windows2[@]} -eq 0 ] && exit

    bsp-layout once even

    for w in "${windows2[@]}"; do
        bspc node "$w" -t tiled
    done
    bspc node "$master2" -p west
    bspc node "$master2" -p east
    bspc node "$master2" -n "$center2"
    i=0
    for w2 in "${stack2[@]}"; do
        if (( i % 2 == 0 )); then
            bspc node "$w2" -n "$left2"
        else
            bspc node "$w2" -n "$right2"
        fi
        ((i++))
    done
    bspc node "$left2" -s south
    bspc node "$right2" -s south
    bspc node "$center2" -f

    if bspc query -N -n ".local.!hidden" -d focused | grep -qx "$LAST_WIN"; then
        bspc node "$LAST_WIN" -f
    fi
    [ -n "$FOCUSED_WIN" ] && bspc node "$FOCUSED_WIN" -f
    bspc node "$(bspc query -N -n focused)" -s "$(bspc query -N -n biggest.local)"

    bsp-layout once even
    bspc node -z left -280 0
    bspc node -z right 280 0

    exit
fi


# 8 windows
if [ "$windowcount" -eq 8 ]; then

DESKTOP=$(bspc query -D -d focused)
FOCUSED_WIN=$(bspc query -N -n focused)
LAST_WIN=$(bspc query -N -n last)
TERM_TRACK_FILE="/tmp/bsp-center_master_spawned_terminal_$DESKTOP"
PID_FILE="$HOME/.cache/bsp-center_master_terminal_pid_$DESKTOP"

"$TERMINAL" >/dev/null 2>&1 &
PID=$!
printf '%s\n' "$PID" > "$HOME/.cache/bsp-center_master_terminal_pid_$DESKTOP"

windows=($(bspc query -N -n .window.!floating.!hidden -d focused))
master=${windows[0]}
stack=("${windows[@]:1}")
cols=($(bspc query -N -n .leaf -d focused))
left=${cols[0]}
center=${cols[1]}
right=${cols[2]}
# 0 window , exit
[ ${#windows[@]} -eq 0 ] && exit

   #bsp-layout once even

    for w in "${windows[@]}"; do
        bspc node "$w" -t tiled
    done
    bspc node "$master" -p west
    bspc node "$master" -p east
    bspc node "$master" -n "$center"
    i=0
    for w in "${stack[@]}"; do
        if (( i % 2 == 0 )); then
            bspc node "$w" -n "$left"
        else
            bspc node "$w" -n "$right"
        fi
        ((i++))
    done
    bspc node "$left" -s south
    bspc node "$right" -s south
    bspc node "$center" -f

windows2=($(bspc query -N -n .window.!floating.!hidden -d focused))
master2=${windows2[0]}
stack2=("${windows2[@]:1}")
cols2=($(bspc query -N -n .leaf -d focused))
left2=${cols2[0]}
center2=${cols2[1]}
right2=${cols2[2]}
# 0 window , exit
[ ${#windows2[@]} -eq 0 ] && exit

    bsp-layout once even

    for w in "${windows2[@]}"; do
        bspc node "$w" -t tiled
    done
    bspc node "$master2" -p west
    bspc node "$master2" -p east
    bspc node "$master2" -n "$center2"
    i=0
    for w2 in "${stack2[@]}"; do
        if (( i % 2 == 0 )); then
            bspc node "$w2" -n "$left2"
        else
            bspc node "$w2" -n "$right2"
        fi
        ((i++))
    done
    bspc node "$left2" -s south
    bspc node "$right2" -s south
    bspc node "$center2" -f

    kill -KILL "$PID"
    rm -f "$PID_FILE"

    [ -n "$FOCUSED_WIN" ] && bspc node "$FOCUSED_WIN" -f
    bspc node "$(bspc query -N -n focused)" -s "$(bspc query -N -n biggest.local)"


    bspc node -z left -200 0
    bspc node -z right 200 0
    bspc node -s west
    bspc node -s west
    bspc node -s west
    bspc node -s west
    bspc node -s west
    bspc node -s west
    bspc node -z right -30 0
    bspc node -s east
    bspc node -z right -20 0
    bspc node -z left -60 0
    bspc node -s east
    bspc node -s east
    bspc node -s east
    bspc node -s east
    bspc node -s east
    bspc node -s east
    bspc node -s east
    bspc node -s east
    bspc node -s east
    bspc node -s west
    bspc node -s south
    bspc node -s south
    bspc node @parent -R -90
    bspc node -s east
    bspc node @parent -R -90
    bspc node -s west
    bspc node -s west
    bspc node @parent -R -90
    bspc node -s east
    bsp-layout once even
    bspc node -z left -376 0
    bspc node -z right 206 0
   #bspc node -z left 20 0
   #bspc node @parent -R 90
   #bspc node -s west
   #bspc node -z left 20 0
   #bspc node -s west
   #bspc node @parent -R 90
   #bspc node -z left -250 0
   #bspc node -z right 250 0

    if bspc query -N -n ".local.!hidden" -d focused | grep -qx "$LAST_WIN"; then
        bspc node "$LAST_WIN" -f
    fi
    [ -n "$FOCUSED_WIN" ] && bspc node "$FOCUSED_WIN" -f

    exit
fi



# 9 windows
if [ "$windowcount" -eq 9 ]; then

DESKTOP=$(bspc query -D -d focused)
FOCUSED_WIN=$(bspc query -N -n focused)
LAST_WIN=$(bspc query -N -n last)
TERM_TRACK_FILE="/tmp/bsp-center_master_spawned_terminal_$DESKTOP"
PID_FILE="$HOME/.cache/bsp-center_master_terminal_pid_$DESKTOP"

windows=($(bspc query -N -n .window.!floating.!hidden -d focused))
master=${windows[0]}
stack=("${windows[@]:1}")
cols=($(bspc query -N -n .leaf -d focused))
left=${cols[0]}
center=${cols[1]}
right=${cols[2]}
# 0 window , exit
[ ${#windows[@]} -eq 0 ] && exit

    for w in "${windows[@]}"; do
        bspc node "$w" -t tiled
    done
    bspc node "$master" -p west
    bspc node "$master" -p east
    bspc node "$master" -n "$center"
    i=0
    for w in "${stack[@]}"; do
        if (( i % 2 == 0 )); then
            bspc node "$w" -n "$left"
        else
            bspc node "$w" -n "$right"
        fi
        ((i++))
    done
    bspc node "$left" -s south
    bspc node "$right" -s south
    bspc node "$center" -f

windows2=($(bspc query -N -n .window.!floating.!hidden -d focused))
master2=${windows2[0]}
stack2=("${windows2[@]:1}")
cols2=($(bspc query -N -n .leaf -d focused))
left2=${cols2[0]}
center2=${cols2[1]}
right2=${cols2[2]}
# 0 window , exit
[ ${#windows2[@]} -eq 0 ] && exit

    bsp-layout once even

    for w in "${windows2[@]}"; do
        bspc node "$w" -t tiled
    done
    bspc node "$master2" -p west
    bspc node "$master2" -p east
    bspc node "$master2" -n "$center2"
    i=0
    for w2 in "${stack2[@]}"; do
        if (( i % 2 == 0 )); then
            bspc node "$w2" -n "$left2"
        else
            bspc node "$w2" -n "$right2"
        fi
        ((i++))
    done
    bspc node "$left2" -s south
    bspc node "$right2" -s south
    bspc node "$center2" -f

    [ -n "$FOCUSED_WIN" ] && bspc node "$FOCUSED_WIN" -f
    bspc node "$(bspc query -N -n focused)" -s "$(bspc query -N -n biggest.local)"


    bspc node -z left -200 0
    bspc node -z right 200 0
    bspc node -s west
    bspc node -s west
    bspc node -s west
    bspc node -s west
    bspc node -s west
    bspc node -s west
    bspc node -z right -30 0
    bspc node -s east
    bspc node -z right -20 0
    bspc node -z left -60 0
    bspc node -s east
    bspc node -s east
    bspc node -s east
    bspc node -s east
    bspc node -s east
    bspc node -s east
    bspc node -s east
    bspc node -s east
    bspc node -s east
    bspc node -s west
    bspc node -s south
    bspc node -s south
    bspc node @parent -R -90
    bspc node -s east
    bspc node @parent -R -90
    bspc node -s west
    bspc node -s west
    bspc node @parent -R -90
    bspc node -s east
    bsp-layout once even
    bspc node -z left -300 0
    bspc node -z right 300 0

    if bspc query -N -n ".local.!hidden" -d focused | grep -qx "$LAST_WIN"; then
        bspc node "$LAST_WIN" -f
    fi
    [ -n "$FOCUSED_WIN" ] && bspc node "$FOCUSED_WIN" -f

    exit
fi



if [ "$windowcount" -ge 10 ]; then
  echo "more than 9 windows detected"
  exit
fi


echo "hello loser"
exit
