#!/usr/bin/env bash

DESKTOP=$(bspc query -D -d focused)
LOCKFILE="$HOME/.cache/bspwm-cmaster-$DESKTOP.lock"

# Prevent multiple instances
if [[ -f "$LOCKFILE" ]] && kill -0 "$(cat "$LOCKFILE")" 2>/dev/null; then
    exit 0
fi

# Record current PID in lock file
echo $$ > "$LOCKFILE"

# Ensure lock file is removed when script exits
trap 'rm -f "$LOCKFILE"' EXIT


PID_FILE_LISTEN="$HOME/.cache/bspwm-cmaster-$DESKTOP.pid"

kill $(cat "$PID_FILE_LISTEN") 2>/dev/null
rm -f "$PID_FILE_LISTEN"

jget() {
    key=$1
    shift
    var=${*#*\"$key\":}
    var=${var%%[,\}]*}
    echo "$var"
}

rotate() {
  # Amend the split type so we are arranged correctly.
  node=$1
  want=$2
  have=$(jget splitType "$(bspc query -T -n "$node")")
  have=${have:1:${#have}-2}
  angle=$3

  [ "$have" != "$want" ] && bspc node "$node" -R "$angle"
}

master_size=55

equalize() {
  rotate '@/' vertical 90
  rotate '@/2' horizontal 90
  local right_stack_node=$(bspc query -N '@/2' -n)
  for parent in $(bspc query -N '@/2' -n .descendant_of.!window.!hidden.!floating | grep -v $right_stack_node); do
  rotate $parent horizontal 90
  done

  rotate '@/1/1' horizontal 90
  local left_stack_node=$(bspc query -N '@/1/1' -n)
  for parent in $(bspc query -N '@/1/1' -n .descendant_of.!window.!hidden.!floating | grep -v $left_stack_node); do
  rotate $parent horizontal 90
  done

  bspc node @/2 -B
  bspc node @/1/1 -B

  local mon_width=$(jget width "$(bspc query -T -m)")
  local want=$(( master_size * mon_width / 100 ))
  local have=$(jget width "$(bspc query -T -n $(bspc query -N '@/1/2' -n .descendant_of.window.!hidden.!floating))")
  local diff=$(( want - have ))

  if (( diff > 0 )); then
      if (( window_count % 2 == 1 )); then
          bspc node $(bspc query -N '@/1/2' -n .descendant_of.window.!hidden.!floating) -z left  -$((diff / 2)) 0
          bspc node  $(bspc query -N '@/1/2' -n .descendant_of.window.!hidden.!floating) -z right $((diff / 2)) 0
      else
          bias=$(( diff / window_count ))
          bspc node $(bspc query -N '@/1/2' -n .descendant_of.window.!hidden.!floating) -z left  -$((diff / 2 + bias)) 0
          bspc node $(bspc query -N '@/1/2' -n .descendant_of.window.!hidden.!floating) -z right $((diff / 2 - bias)) 0
      fi
  fi
}

bsp-cmaster-oneshot

{
    while read -r line; do
        # Split the line into fields
        read -r event monitor desktop node action <<< "$line"

        # Only act if the desktop matches
        if [[ "$desktop" == "$DESKTOP" ]]; then
            case "$event" in
                node_add)
                    FOCUSED_WIN=$(bspc query -N -n focused)
                    window_count=$(bspc query -N -n .window.!floating.!hidden.!floating -d focused | wc -l)
                    LEFT_STACK_COUNT=$(bspc query -N '@/1/1' -n .descendant_of.window.!hidden.!floating | wc -l)
                    RIGHT_STACK_COUNT=$(bspc query -N '@/2' -n .descendant_of.window.!hidden.!floating | wc -l)
                    MASTER_NODE_COUNT=$(bspc query -N '@/1/2' -n .descendant_of.window.!hidden.!floating | wc -l)

                    if (( window_count == 1 )); then
                          if pgrep -x bsp-icon-bar >/dev/null; then
                              icon_bar_was_running=true
                              if (( window_count >= 1 )); then
                                  pkill -x bsp-icon-bar
                              fi
                          fi

                          if $icon_bar_was_running; then
                                bsp-icon-bar &
                          fi
                    fi

                    if (( window_count == 2 || window_count == 3 )); then
                          bsp-cmaster-oneshot
                    fi

                    if (( window_count >= 3 )); then
                        if [[ $MASTER_NODE_COUNT -eq 1 ]]; then
                            if [[ $LEFT_STACK_COUNT -eq $RIGHT_STACK_COUNT  ]]; then
                                equalize
                            fi
                            if [[ $LEFT_STACK_COUNT -lt $RIGHT_STACK_COUNT  ]]; then
                                bspc node $FOCUSED_WIN -n @/1/1
                                equalize
                            fi
                            if [[ $LEFT_STACK_COUNT -gt $RIGHT_STACK_COUNT  ]]; then
                                if (( LEFT_STACK_COUNT - 1 == RIGHT_STACK_COUNT )); then
                                    equalize
                                else
                                    bspc node $FOCUSED_WIN -n @/2
                                    equalize
                                fi
                            fi
                        fi
                        if [[ $MASTER_NODE_COUNT -gt 1 ]]; then
                            if [[ $LEFT_STACK_COUNT -eq $RIGHT_STACK_COUNT  ]]; then
                                bspc node $FOCUSED_WIN -n @/1/1
                                equalize
                            fi
                            if [[ $LEFT_STACK_COUNT -lt $RIGHT_STACK_COUNT  ]]; then
                                bspc node $FOCUSED_WIN -n @/1/1
                                equalize
                            fi
                            if [[ $LEFT_STACK_COUNT -gt $RIGHT_STACK_COUNT  ]]; then
                                bspc node $FOCUSED_WIN -n @/2
                                equalize
                            fi
                        fi
                    fi
                    bsp-zoom
                    ;;


                node_remove)
                    FOCUSED_WIN=$(bspc query -N -n focused)
                    window_count=$(bspc query -N -n .window.!floating.!hidden.!floating -d focused | wc -l)
                    LEFT_STACK_COUNT=$(bspc query -N '@/1/1' -n .descendant_of.window.!hidden.!floating | wc -l)
                    RIGHT_STACK_COUNT=$(bspc query -N '@/2' -n .descendant_of.window.!hidden.!floating | wc -l)
                    MASTER_NODE_COUNT=$(bspc query -N '@/1/2' -n .descendant_of.window.!hidden.!floating | wc -l)

                    if (( window_count == 1 )); then
                          if pgrep -x bsp-icon-bar >/dev/null; then
                              icon_bar_was_running=true
                              if (( window_count >= 1 )); then
                                  pkill -x bsp-icon-bar
                              fi
                          fi

                          if $icon_bar_was_running; then
                                bsp-icon-bar &
                          fi
                    fi

                    if (( window_count == 2 || window_count == 3 )); then
                          bsp-cmaster-oneshot
                    fi

                    if (( window_count > 3 )); then
                        if [[ $MASTER_NODE_COUNT -eq 1 ]]; then
                            if [[ $LEFT_STACK_COUNT -eq $RIGHT_STACK_COUNT  ]]; then
                                equalize
                                bspc node @/ -B
                            fi
                            if [[ $LEFT_STACK_COUNT -lt $RIGHT_STACK_COUNT  ]]; then
                                bspc node $(bspc query -N '@/2' -n .descendant_of.window.!hidden.!floating | head -n 1) -n @/1/1
                                equalize
                                bspc node @/ -B
                            fi
                            if [[ $LEFT_STACK_COUNT -gt $RIGHT_STACK_COUNT  ]]; then
                                if (( LEFT_STACK_COUNT - 1 == RIGHT_STACK_COUNT )); then
                                    equalize
                                else
                                    bspc node $(bspc query -N '@/1/1' -n .descendant_of.window.!hidden.!floating | tail -n 1) -n @/2
                                    equalize
                                fi
                            fi
                        fi
                        if [[ $MASTER_NODE_COUNT -gt 1 ]]; then


                                for wid in $(bspc query -N '@/1/2' -n .descendant_of.window.!hidden.!floating); do
                                bspc node "$wid" -n '@/1'
                                done
                                if [[ $LEFT_STACK_COUNT -lt $RIGHT_STACK_COUNT  ]]; then
                                    bspc node $(bspc query -N '@/2' -n .descendant_of.window.!hidden.!floating | head -n 1) -n @/1/1
                                    equalize
                                fi
                                equalize
                                bspc node @/ -B
                        fi

                        equalize
                        bspc node -f $(bspc query -N '@/1/2' -n)
                    fi
                    ;;

                    *)
                        # Ignore other events
                    ;;
            esac
           #bspc node -f $(bspc query -N '@/1/2' -n)
        fi
    done < <(bspc subscribe node_add node_remove)
} &

# Save the PID of the background listener
echo $! > "$PID_FILE_LISTEN"

